---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MysariRaghav/SpringCloudConfigWATolls
#          username:rmysari
#          password:Kill4win
          search-paths:
            - 'station*'



server:
  port: 8888